const Router = require('express')
const router = new Router()
const addingsRouter = require('./addingsRouter')
const appealsRouter = require('./appealsRouter')
const appealStatusesRouter = require('./appealStatusesRouter')
const chatRouter = require('./chatsRouter')
const contactTypesRouter = require('./contactTypesRouter')
const coursesRouter = require('./coursesRouter')
const learningGoalRouter = require('./learningGoalRouter')
const learningGoalTypeRouter = require('./learningGoalTypeRouter')
const lessonStatusRouter = require('./lessonStatusRouter')
const managersRouter = require('./managersRouter')
const messagesRouter = require('./messagesRouter')
const paymentsRouter = require('./paymentsRouter')
const resultsRouter = require('./resultsRouter')
const specializationRouter = require('./specializationRouter')
const studentsRouter = require('./studentsRouter')
const subjectsRouter = require('./subjectsRouter')
const teachersRouter = require('./teachersRouter')
const testCourseRouter = require('./testCourseRouter')
const testingTaskRouter = require('./testingTaskRouter')
const testingTypesRouter = require('./testingTypesRouter')
const testRouter = require('./testsRouter')
const timetableRouter = require('./timetableRouter')
const userContactRouter = require('./userContactRouter')


router.use('/addings', addingsRouter)
router.use('/appeals', appealsRouter)
router.use('/appealStatuses', appealStatusesRouter)
router.use('/chat', chatRouter)
router.use('/contactTypes', contactTypesRouter)
router.use('/courses', coursesRouter)
router.use('/learningGoal', learningGoalRouter)
router.use('/learningGoalType', learningGoalTypeRouter)
router.use('/lessonStatus', lessonStatusRouter)
router.use('/managers', managersRouter)
router.use('/messages', messagesRouter)
router.use('/payments', paymentsRouter)
router.use('/results', resultsRouter)
router.use('/specialization', specializationRouter)
router.use('/students', studentsRouter)
router.use('/subjects', subjectsRouter)
router.use('/teachers', teachersRouter)
router.use('/testCourse', testCourseRouter)
router.use('/testingTask', testingTaskRouter)
router.use('/testingTypes', testingTypesRouter)
router.use('/test', testRouter)
router.use('/timetable', timetableRouter)
router.use('/userContact', userContactRouter)

module.exports = router