export const DATABASE_ROUTE = '/database'
export const MANAGER_LOGIN_ROUTE = '/managerLogin'
export const MANAGER_REGISTRATION_ROUTE = '/managerRegistration'
export const CLIENT_SUPPORT_ROUTE = '/clientSupport'
export const NEW_USERS_ROUTE = '/newUsers'
export const MAIN_PAGE_ROUTE = '/'